permalink: /:year/:month/:day/:title/

# Site settings
title: Mincong Huang
title_suffix: Mincong's Blog
author_name: Mincong Huang
author_first_name: Mincong
author_last_name: Huang
email: mincong.h@gmail.com
description: > 
  Hi, welcome to my blog! I'm junior software engineer at Nuxeo. My blogs are
  expriences that I met during different projects. Most of them will be related
  to Java. My opinions are my own, not Nuxeo's.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mincong-h.github.io"
twitter_username: mincong_h
github_username:  mincong-h
tagline: 'Blog'
img_url: /assets/logo-github.png
img_width: 300
img_height: 300

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

# Custom vars
version: 1.1.0
google_analytics: UA-87129300-1

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
