# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Parlalinks
permalink: /:year/:month/:day/:title/

# Site settings
title: Mincong HUANG
email: mincong.h@gmail.com
description: > 
  Hi, welcome to my blog ! I'm a postgraduate CS student who love programming.
  My blogs represent some problems or expriences that I met during projects or 
  intern. Most of them will be related to Java, Android, Excel VBA and SQL. 
  Hope you enjoy them !

# this means to ignore newlines until "baseurl:"
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mincong-h.github.io"
twitter_username: mincong_h
github_username:  mincong-h
tagline: 'blog' # lanyon theme
paginate: 5

# Each post automatically takes the first block of text, from the beginning of
# the content of the first occurrence of excerpt_separator, and sets it as the 
# post.excerpt. Take the above example of an index of posts.
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown # basic theme

# Custom vars
version: 1.1.0
google_analytics: UA-87129300-1
facebook_id: 1788552244732928

# Gems
gems:
  - jekyll-paginate
  - jekyll-redirect-from
