permalink: /:year/:month/:day/:title/

# Site settings
title: Mincong Huang
title_suffix: Mincong's Blog
author: Mincong Huang
author_first_name: Mincong
author_last_name: Huang
email: mincong.h@gmail.com
description: > 
  Hi, welcome to my blog! I'm a software engineer at Datadog. I write blog posts
  in my free time. My blogs are
  bits and pieces of my tech journey. Most of them are related
  to Java. Hope you enjoy them! My opinions are my own, not Datadog's. This blog
  is powered by Jekyll, a simple, blog-aware, static sites solution.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mincong-h.github.io"
twitter_username: mincong_h
github_username:  mincong-h
tagline: 'Blog'
image: /assets/logo-github.png
img_width: 300
img_height: 300

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

# Custom vars
version: 1.1.0
google_analytics: UA-87129300-1

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
