permalink: /:year/:month/:day/:title/

# Site settings
title: Mincong HUANG
email: mincong.h@gmail.com
description: > 
  Hi, welcome to my blog! I'm junior software engineer at Nuxeo. My blogs are
  expriences that I met during different projects. Most of them will be related
  to Java. My opinions are my own, not Nuxeo's.

# this means to ignore newlines until "baseurl:"
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mincong-h.github.io"
twitter_username: mincong_h
github_username:  mincong-h
tagline: 'blog' # lanyon theme
paginate: 5

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

# Custom vars
version: 1.1.0
google_analytics: UA-87129300-1
facebook_id: 1788552244732928

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
