# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Parlalinks
permalink: pretty # URL template /:categories/:year/:month/:day/:title/

# Site settings
title: Mincong HUANG
email: mincong.h@gmail.com
description: > 
  Hi, welcome to my blog ! I'm a postgraduate CS student who love programming.
  My blogs represent some problems or expriences that I met during projects or 
  intern. Most of them will be related to Java, Android, Excel VBA and SQL. 
  Hope you enjoy them !
# this means to ignore newlines until "baseurl:"
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mincong-h.github.io" # the base hostname & protocol for your site
twitter_username: mincong_h
github_username:  mincong-h
tagline: 'blog' # lanyon theme
paginate: 5
# About/contact
# author:
# name: Mincong Huang
# url: https://twitter.com/mincong_h
# email: mincong.h@gmail.com

# Build settings
markdown: kramdown # basic theme

# Custom vars
version: 1.1.0

# Gems
gems: [jekyll-paginate]
